on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: "graalvm-community"
          java-version: "25"

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          lein: 2.12.0

      - name: Clojure Dependencies Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
          key: clojure-${{ hashFiles('project.clj') }}
          restore-keys: clojure-

      - name: Run tests
        run: lein test
