on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '24'

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          lein: 2.11.2

      - name: Clojure Dependencies Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
          key: clojure-${{ hashFiles('project.clj') }}
          restore-keys: clojure-

      - name: Run tests
        run: lein test
